# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_auto_20171225_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created',)},
        ),
    ]
