# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0005_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='line',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
