# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='text',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='line',
            name='create_date',
        ),
        migrations.AddField(
            model_name='line',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
