# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lines', '0008_auto_20180122_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('desc', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='lines.Line')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='line',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
