# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0009_auto_20180220_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('end',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('due',)},
        ),
    ]
